### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by ImAlwaysInFaMouS** [mcrossen/factorio-pi#1]
Followed commands to the letter, changed config and still not boot.
- also where do we find the core dump?

pi 4B 4gb

**Comment by mcrossen** [comment]
This is a known issue which is why I included the warning at the top of the instructions about it. I'm not sure how to fix yet.

We're you able to get any logs from the server before it crashed?

**Comment by ImAlwaysInFaMouS** [comment]
I'll try again and see if i can dig anything out... just looking at this https://www.raspberrypi.org/forums/viewtopic.php?t=275114 is this kind of the same thing we need to do to get the x86 stuff? he says the qemu is broken and you should build from source not apt-get.

**Comment by mcrossen** [comment]
Yea. That's the same idea as what I'm trying to do here.

If qemu is broken on pi then that would be an extremely likely reason for these segfaults. I can look into that in a week or so when I get home and have access to my pi again. Thanks for showing me!

In the meantime you could try following that tutorial you linked and change the teamspeak server to a factorio server or whatever you want to run.

**Comment by ImAlwaysInFaMouS** [comment]
that is my next step, ill let you know how it goes

**Comment by ImAlwaysInFaMouS** [comment]
[https://www.raspberrypi.org/forums/viewtopic.php?t=275114]
The only problem I ran into building: 
"mkdir /srv/chroot/stretch_x86"
Should be 
"mkdir -p /srv/chroot/stretch_x86" (so we make the parent dirs)

[Factorio install]
install xz-utils so we can untar the the tar.xz
"tar -zJf ~/factorio-server.tar.xz -C ~/"
Not sure we need -zjf as it wouldnt work so i changed it to -xf.
---
Now for the bad news, apt installing:
"apt install systemd-container qemu-user-static debootstrap"
just results in this after all commands:
"bash: /usr/bin/systemd-nspawn: Too many levels of symbolic links"
https://pastebin.com/tcf7djvf 

idk what to do now... I'm noob really

**Comment by ImAlwaysInFaMouS** [comment]
https://wiki.factorio.com/Multiplayer

Maybe just use a centOS image? :/

**Comment by mcrossen** [comment]
Your pastebin seems to indicate that the error occurs when installing a required dependency: dbus. Hard for me to debug without my own computers with me at the moment. I couldn't find a good google source on installing dbus on a pi.

**Comment by ImAlwaysInFaMouS** [comment]
https://stackoverflow.com/questions/43085699/update-dbus-on-raspberry-pi

**Comment by mcrossen** [comment]
newer qemu and debootrap chroot seems to fix this issue
