### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by Cloudninjakip** [mcrossen/factorio-pi#2]
`execv(/factorio/bin/x64/factorio) failed: Exec format error
Container factorio-runtime failed with error code 1.`

**Comment by mcrossen** [comment]
I'm able to reproduce the error by running the guide on a fresh pi install. Its a new error that I haven't seen before which means its likely introduced in a new version of the factorio server or qemu. I don't know how to fix it, sorry. But I want to add additional information that might help someone smarter than me

Notice the first reported error is "Source directory /dev/fd/10 does not exist or is not a directory."
```
27.578 Loading map /
27.873 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "Source directory /dev/fd/10 does not exist or is not a directory."
27.874 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(CreatingGame) to(InitializationFailed)
27.875 Info CommandLineMultiplayer.cpp:209: Exit point.
27.985 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
27.985 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(InitializationFailed) to(Closed)
28.796 Info UDPSocket.cpp:218: Closing socket
28.806 Goodbye
Container factorio-runtime failed with error code 1.
```

**Comment by mcrossen** [comment]
I pushed instructions to run factorio on a pi via docker container. This new way works much better for me so I removed the instructions for the manual method. As a result, I'm going to close this issue now. Please feel free to create a new issue if the new docker instructions also have issues for you.
