### ISSUE TITLE
This break my system

### ISSUE THREAD

**Issue by Stargateur** [mcrossen/factorio-pi#4]
I don't know how but this broke my system and I can't fix it, I really don't know if this is specific tuto or install qemu and everything, I also try to check for kms support but one reboot and my system refuse to boot with "err format file" on the emergency service shell... so I can't access to any log. After 3 hours of attempt I give up and disadvice you to follow this tutorial.

![photo_2021-04-17_01-47-30](https://user-images.githubusercontent.com/7503742/115098527-c8244980-9f30-11eb-913b-fa2716b398ac.jpg)

Notice the "Succeeded" that troll me since 2 hours.

**Comment by mcrossen** [comment]
wow. I'm sorry you had this experience. I don't know why this would've happened. I intended this guide to be a work in progress that others could help work the kinks out of, but I never thought it was damaging in any way.

**Comment by mcrossen** [comment]
Let me make that 'work in progress' notion more clear in the warning on the top of the guide.

**Comment by Stargateur** [comment]
I do not blame you in anyway.

I suspect `sudo systemd-nspawn` to have install thing but It really hard to understand what it does exactly and how to remove thing it have done at hand, cause I don't have any shell to fix or understand what happening.

**Comment by mcrossen** [comment]
I pushed instructions to run factorio on a pi via docker container. This new way works much better for me so I removed the instructions for the manual method. As a result, I'm going to close this issue now. Please feel free to create a new issue if the new docker instructions also have issues for you.
