### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped Segmentation fault

### ISSUE THREAD

**Issue by xsestech** [mcrossen/factorio-pi#5]
Here is console output: https://pastebin.com/Y4LQ3QFv
Here is log: https://pastebin.com/cB0qb6is

**Comment by alex318** [comment]
I have the same issue. Did you find a solution for it in the meantime?

**Comment by xsestech** [comment]
No, I didn't

**Comment by jacobtyq** [comment]
I encountered the same issue.

So instead of using 
```
sudo qemu-debootstrap --arch=amd64 stable ~/factorio-runtime/ --variant=buildd
```

I went with
```
// To use Debian 9 (Stretch)
sudo qemu-debootstrap --arch=amd64 stretch ~/factorio-runtime/ --variant=buildd

```

And managed to install the base system. Console output: https://pastebin.com/zetLb2CV

However, running the next command results in the same error

```
sudo systemd-nspawn -D ~/factorio-runtime --bind=/home/$USER/factorio:/factorio /factorio/bin/x64/factorio --start-server-load-latest /factorio/saves/ --server-settings /factorio/data/server-settings.json
Spawning container factorio-runtime on /home/pi/factorio-runtime.
Press ^] three times within 1s to kill container.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by RBGamer100** [comment]
I ran into both of these issues described here a couple weeks ago, just got around to installing Raspbian OS Full 64bit today and other than having to drop the `--variant=buildd` part of the qemu command the server has finally started up after creating a save

**Comment by mcrossen** [comment]
I pushed instructions to run factorio on a pi via docker container. This new way works much better for me so I removed the instructions for the older/manual method. I'm going to close this issue because it relates to the old method. Please feel free to create a new issue if the new docker instructions also have issues for you.
